In [1]:
import warnings
warnings.filterwarnings("ignore")
# For connect to google sheet
import gspread
from oauth2client.service_account import ServiceAccountCredentials
from df2gspread import df2gspread as d2g

In [2]:
import pandas as pd

In [3]:
# Configure the connection 
scope = ['https://spreadsheets.google.com/feeds']

# Give the path to the Service Account Credential json file 
credentials = ServiceAccountCredentials.from_json_keyfile_name('service_account_GS.json',
                                                               scope
                                                              )
# Authorise your Notebook
gc = gspread.authorize(credentials)

# The sprad sheet ID, which can be taken from the link to the sheet
spreadsheet_key = '1vNnbAl7kMQHeL-UbkL8hTY93Z_3areu195dUuV7ooMA'
#

In [11]:
#df = pd.read_csv('client_ids.csv',index_col = False)
from df2gspread import gspread2df as g2d
df = g2d.download(gfile=spreadsheet_key,wks_name = 'histo',credentials=credentials, col_names=True, row_names=True)

In [12]:
df

,week_,date,Ride_distance_sum,Ride_moving_time_sum,Ride_distance_max,Run_distance_sum,Run_distance_max,Run_moving_time_sum,Swim_distance_sum,Swim_moving_time_sum,Swim_distance_max
2022,24,2022-06-13 00:00:00,94.4,3.7,24.7,27.1,15.0,2.6,4.5,1.4,2.5
2022,23,2022-06-06 00:00:00,198.0,7.0,83.4,52.4,18.2,5.1,6.0,2.0,2.0
2022,22,2022-05-30 00:00:00,109.6,4.7,13.0,37.8,15.9,3.3,4.0,1.4,2.0
2022,21,2022-05-23 00:00:00,195.4,8.7,101.2,22.5,10.0,2.2,3.6,1.2,2.0
2022,20,2022-05-16 00:00:00,99.5,3.9,38.7,31.0,10.4,3.1,1.4,0.5,1.4
...,...,...,...,...,...,...,...,...,...,...,...
2020,7,2020-02-17 00:00:00,100.9,4.2,100.9,0.0,0.0,0.0,0.0,0.0,0.0
2020,5,2020-02-03 00:00:00,172.4,7.3,172.4,0.0,0.0,0.0,0.0,0.0,0.0
2019,28,2019-07-15 00:00:00,26.0,0.9,13.0,0.0,0.0,0.0,0.0,0.0,0.0
2019,25,2019-06-24 00:00:00,20.8,0.8,20.8,0.0,0.0,0.0,0.0,0.0,0.0
2019,19,2019-05-13 00:00:00,45.6,1.7,20.9,0.0,0.0,0.0,0.0,0.0,0.0