In [64]:
import requests
import pandas as pd

import time
import datetime

from dateutil import parser
import calendar

import os
import config 
import glob

import selenium
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager


from function import log

In [65]:
log('------------------------Beginning--------------------')
log('Launching Job A')
# get email & password
email_user = config.USER_EMAIL
password = config.USER_PASS

# access strava and authentificate
s=Service(ChromeDriverManager().install())
driver = webdriver.Chrome(service=s)
driver.get("http://www.strava.com/login")


css_selector = 'button[class="btn-accept-cookie-banner"]'
driver.find_element(by=By.CSS_SELECTOR, value=css_selector).click()

search_box = driver.find_element(By.ID,'email')

search_box.send_keys(email_user)

pass_box = driver.find_element(By.ID,'password')
pass_box.send_keys(password)

css_selector_2 = 'button[class="btn btn-primary"]'
cookie_to_click = driver.find_element(by=By.CSS_SELECTOR, value=css_selector_2)
try :
    cookie_to_click.click()
except NoSuchElementException:
    pass
    

#aller sur la page 
url_auth='https://www.strava.com/oauth/authorize?client_id=78772&response_type=code&redirect_uri=http://localhost/exchange_token&approval_prompt=force&scope=profile:read_all,activity:read_all'
driver.get(url_auth)
#cliquer sur 'Authorize'
#id_ = 'button[id="authorize"]'
driver.find_element(By.ID, "authorize").click()
#prendre l'access token dans driver.current_url à http://localhost/exchange_token?state=&code=de6eb8529ce8ee0271941f2c5d0dd872d5feb376&scope=read,activity:read_all,profile:read_all
url_code = driver.current_url
#le mettre dans code
code = url_code.split("&")[1].replace("code=","")
driver.quit()

====== WebDriver manager ======

2022-Jun-17-13:47:11 , ------------------------Beginning--------------------;
2022-Jun-17-13:47:11 , Launching Job A;

Current google-chrome version is 102.0.5005
Get LATEST chromedriver version for 102.0.5005 google-chrome
Driver [/Users/florianniclause/.wdm/drivers/chromedriver/mac64/102.0.5005.61/chromedriver] found in cache

In [66]:
import requests
import json
import config
# Make Strava auth API call with your 
# client_code, client_secret and code
response = requests.post(
                    url = 'https://www.strava.com/oauth/token',
                    data = {
                            'client_id': config.client_ID,
                            'client_secret': config.client_secret,
                            'code': code,
                            'grant_type': 'authorization_code'
                            }
                )
#Save json response as a variable
strava_tokens = response.json()
# Save tokens to file
with open('strava_tokens.json', 'w') as outfile:
    json.dump(strava_tokens, outfile)
# Open JSON file and print the file contents 
# to check it's worked properly
with open('strava_tokens.json') as check:
  data = json.load(check)

In [67]:
access_token = data['access_token']

In [68]:
### initialization of activities table
url_init = f"https://www.strava.com/api/v3/athlete/activities?access_token={access_token}&per_page=200"
payload={}
headers = {
  'Cookie': '_strava4_session=633nr333v5vqncotecis88kabfigqpff'
}

response = requests.request("GET", url_init, headers=headers, data=payload)
activities_df = pd.json_normalize(response.json())

In [69]:
activities_df.iloc[-1]['start_date']

'2022-04-05T10:34:45Z'

In [70]:
s = activities_df.iloc[-1]['start_date']
parsed_date = parser.parse(s)
timestamp = []
timestamp.append(calendar.timegm(parser.parse(s).timetuple()))


#### loop to get all activities
while True:
    url = f"https://www.strava.com/api/v3/athlete/activities?access_token={access_token}&before="+str(timestamp[-1])+"&per_page=200"
    response = requests.request("GET", url, headers=headers, data=payload)
    activities = pd.json_normalize(response.json())
    activities_df = pd.concat([activities_df, activities],ignore_index=True)
    
    s = activities_df.iloc[-1]['start_date']
    parsed_date = parser.parse(s)
    timestamp.append(calendar.timegm(parser.parse(s).timetuple()))
    
    if timestamp[-1]==timestamp[-2]:
        break

In [71]:
activities_df

,resource_state,name,distance,moving_time,elapsed_time,total_elevation_gain,type,sport_type,workout_type,id,...,athlete.id,athlete.resource_state,map.id,map.summary_polyline,map.resource_state,average_watts,max_watts,weighted_average_watts,kilojoules,device_watts
0,2,Course à pied dans l'après-midi,9267.4,2739,2899,19.0,Run,Run,NaN,7319456006,...,41974409,1,a7319456006,}`biGcm{G`@?p@JLZG\JHh@B~@Cf@T`BCXIn@N`@AjAw@L...,2,NaN,NaN,NaN,NaN,NaN
1,2,Sortie vélo dans l'après-midi,10454.4,1577,1656,97.0,Ride,Ride,NaN,7315127255,...,41974409,1,a7315127255,u|{hGy}kG_@][a@Sa@y@{@IS?Sf@eBHc@Tm@@K@WEUEEUM...,2,167.3,604.0,177.0,263.8,True
2,2,Course à pied dans l'après-midi,3215.6,1100,1108,26.0,Run,Run,NaN,7315125043,...,41974409,1,a7315125043,ep{hG}fpGc@}@}@AGcA@WKo@@QFGh@TZb@\PPNZL@CBHEp...,2,NaN,NaN,NaN,NaN,NaN
3,2,Natation le midi,2525.0,2836,3379,0.0,Swim,Swim,NaN,7315123891,...,41974409,1,a7315123891,None,2,NaN,NaN,NaN,NaN,NaN
4,2,Course à pied le midi,2814.3,949,962,7.0,Run,Run,NaN,7315122641,...,41974409,1,a7315122641,wb|hG__lGAm@AICAELk@p@]Fa@CYDWd@MLVb@TRD?DIA]S...,2,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1040,2,Décrassage du dimanche soir,13040.5,1572,1591,61.9,Ride,Ride,10.0,2532444106,...,41974409,1,a2532444106,aabiGei{GV?\\VSf@In@LJJxA@j@Or@@RMr@DbA[d@BVYh...,2,NaN,NaN,NaN,NaN,False
1041,2,Montgiscard 2ème,20781.6,2842,2857,78.5,Ride,Ride,10.0,2474195665,...,41974409,1,a2474195665,{dbiGoi{GnDRh@MCMdB\lBDp@UbCB`@_At@W~AqAnAgBhG...,2,NaN,NaN,NaN,NaN,False
1042,2,Sortie à vélo en soirée,4241.0,672,3874752,34.6,Ride,Ride,10.0,2474034380,...,41974409,1,a2474034380,y`biGaj{GFFN@XJJTd@E|@H\?pBIzAFLATULATBZW?ORYF...,2,NaN,NaN,NaN,NaN,False
1043,2,Sortie à vélo dans l'après-midi,20370.2,2817,2817,73.8,Ride,Ride,10.0,2351795861,...,41974409,1,a2351795861,sdhhGotqHbA`AQLuAlCa@Xm@v@yBbFiA|D_BdHwDlLeLdZ...,2,NaN,NaN,NaN,NaN,False
1044,2,Sortie à vélo dans l'après-midi,20939.3,2616,2616,75.1,Ride,Ride,12.0,2351676900,...,41974409,1,a2351676900,s`biGcj{Gh@GRXtB\tAQLT\@`@[r@JxCcBbAkBpAk@zBgB...,2,NaN,NaN,NaN,NaN,False

In [55]:
activities_df['type_bis']=activities_df['type']
activities_df['type']=activities_df['type'].replace('VirtualRide','Ride').replace('VirtualRun','Run')

from datetime import datetime, timezone
import calendar
from function import start_date, get_weekday, get_day, get_week, get_month, get_year
"""def start_date(date_):
    return datetime.fromisoformat(date_[:-1])
def get_weekday(date_):
    #date_=datetime.fromisoformat(date_[:-1] + '+00:00').astimezone(timezone.utc)
    return calendar.day_name[date_.weekday()]
def get_day(date_):
    return date_.day
def get_month(date_):
    return date_.month
def get_year(date_):
    return date_.year
def get_week(date_):
    return date_.week

def localize_time(time_):
    return time_.tz_localize('Europe/Paris')
"""
#localize time
activities_df['start_date_local']=activities_df['start_date_local'].apply(start_date).apply(localize_time)

activities_df['weekday']=activities_df['start_date_local'].apply(get_weekday)
activities_df['day']=activities_df['start_date_local'].apply(get_day)
activities_df['week']=activities_df['start_date_local'].apply(get_week)
activities_df['month']=activities_df['start_date_local'].apply(get_month)
activities_df['year']=activities_df['start_date_local'].apply(get_year)

In [ ]:
activities_df.to_csv('data/activities.csv', index=False)

In [10]:
df_daily = activities_df.groupby(['type','start_date_local'],as_index=False).agg({'distance': ['sum','mean', 'min', 'max'],'moving_time': ['sum','mean', 'min', 'max'],'total_elevation_gain': ['sum','mean', 'min', 'max']}).sort_values(by='start_date_local',ascending=False)

In [11]:
#columns = df_daily.columns.tolist()
df_daily.columns = ['_'.join(col) for col in df_daily.columns]

In [12]:
df_daily

,type_,start_date_local_,distance_sum,distance_mean,distance_min,distance_max,moving_time_sum,moving_time_mean,moving_time_min,moving_time_max,total_elevation_gain_sum,total_elevation_gain_mean,total_elevation_gain_min,total_elevation_gain_max
940,Run,2022-06-16 17:49:01+02:00,9267.4,9267.4,9267.4,9267.4,2739,2739,2739,2739,19.0,19.0,19.0,19.0
558,Ride,2022-06-15 17:33:12+02:00,10454.4,10454.4,10454.4,10454.4,1577,1577,1577,1577,97.0,97.0,97.0,97.0
939,Run,2022-06-15 13:29:56+02:00,3215.6,3215.6,3215.6,3215.6,1100,1100,1100,1100,26.0,26.0,26.0,26.0
1024,Swim,2022-06-15 12:28:34+02:00,2525.0,2525.0,2525.0,2525.0,2836,2836,2836,2836,0.0,0.0,0.0,0.0
938,Run,2022-06-15 12:08:14+02:00,2814.3,2814.3,2814.3,2814.3,949,949,949,949,7.0,7.0,7.0,7.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10,Ride,2019-07-14 20:25:17+02:00,13040.5,13040.5,13040.5,13040.5,1572,1572,1572,1572,61.9,61.9,61.9,61.9
9,Ride,2019-06-23 15:35:57+02:00,20781.6,20781.6,20781.6,20781.6,2842,2842,2842,2842,78.5,78.5,78.5,78.5
8,Ride,2019-05-09 19:16:20+02:00,4241.0,4241.0,4241.0,4241.0,672,672,672,672,34.6,34.6,34.6,34.6
7,Ride,2019-05-08 17:17:53+02:00,20370.2,20370.2,20370.2,20370.2,2817,2817,2817,2817,73.8,73.8,73.8,73.8
6,Ride,2019-05-08 16:26:32+02:00,20939.3,20939.3,20939.3,20939.3,2616,2616,2616,2616,75.1,75.1,75.1,75.1

Loading the dataframe on Googlesheet

In [13]:
import warnings
warnings.filterwarnings("ignore")
# For connect to google sheet
import gspread
from oauth2client.service_account import ServiceAccountCredentials
from df2gspread import df2gspread as d2g

In [14]:
# Configure the connection 
scope = ['https://spreadsheets.google.com/feeds']

# Give the path to the Service Account Credential json file 
credentials = ServiceAccountCredentials.from_json_keyfile_name('service_account_GS.json',
                                                               scope
                                                              )
# Authorise your Notebook
gc = gspread.authorize(credentials)

# The sprad sheet ID, which can be taken from the link to the sheet
spreadsheet_key = '1vNnbAl7kMQHeL-UbkL8hTY93Z_3areu195dUuV7ooMA'
#

In [15]:
# Set the sheet name you want to upload data to and the start cell where the upload data begins 
wks_name = 'day'
cell_of_start_df = 'A1'
# upload the dataframe of the clients we want to delete
d2g.upload(df_daily,
           spreadsheet_key,
           wks_name,
           credentials=credentials,
           col_names=True,
           row_names=False,
           start_cell = cell_of_start_df,
           clean=True)

Weekly

In [16]:
df_weekly = activities_df.groupby(['type','week','year'],as_index=False).agg({'distance': ['sum','max'],'moving_time': ['sum']}).sort_values(by=['year','week'],ascending=[False,False])

df_weekly.columns = ['_'.join(col) for col in df_weekly.columns]
df_weekly.loc[:,['distance_sum','distance_max']]=df_weekly.loc[:,['distance_sum','distance_max']]/1000
df_weekly.loc[:,['moving_time_sum']]=df_weekly.loc[:,['moving_time_sum']]/(60*60)

#activities to keep
some_values=['Run','Ride','Swim']

df_weekly=df_weekly.loc[df_weekly['type_'].isin(some_values)]


df_weekly=df_weekly.pivot_table(df_weekly, ['week_','year_'], 'type_',fill_value=0)#[[cols]]#.sort_index(axis='columns', level='type_')
cols = df_weekly.columns.tolist()

df_weekly

cols = [('distance_sum', 'Ride'), ('distance_sum', 'Run'), ('distance_sum', 'Swim'), ('distance_max', 'Ride'), ('distance_max', 'Run'), ('distance_max', 'Swim'), ('moving_time_sum', 'Ride'), ('moving_time_sum', 'Run'), ('moving_time_sum', 'Swim')]
#df_weekly.loc[:,cols]

In [17]:
columns = df_weekly.columns.tolist()
df_weekly.columns = ['_'.join(tuple(reversed(list(col)))) for col in columns]

col_to_drop=[]

df_weekly=df_weekly.reset_index(level=0).reset_index(level=0).sort_values(by=['year_', 'week_'], ascending=True).drop(labels=col_to_drop,axis=1).round(1)

In [18]:
df_weekly=df_weekly[['year_', 'week_', 'Ride_distance_sum','Ride_moving_time_sum', 'Ride_distance_max', 
                          'Run_distance_sum','Run_moving_time_sum','Run_distance_max',
                          'Swim_distance_sum', 'Swim_moving_time_sum','Swim_distance_max']
                   ]

In [19]:
df_weekly=df_weekly.reset_index(drop=True)

In [20]:
import datetime
d = str(df_weekly.year_[0])+'-W'+str(df_weekly.week_[0])
r = datetime.datetime.strptime(d + '-1', "%Y-W%W-%w")

In [21]:
df_weekly['date_']=df_weekly.year_.map(str)+'-W'+df_weekly.week_.map(str)+ '-1'

In [22]:
df_weekly['date_']

0      2019-W19-1
1      2019-W25-1
2      2019-W28-1
3       2020-W5-1
4       2020-W7-1
          ...
118    2022-W20-1
119    2022-W21-1
120    2022-W22-1
121    2022-W23-1
122    2022-W24-1
Name: date_, Length: 123, dtype: object

In [23]:
df_weekly.insert(2,'date',df_weekly['date_'])
df_weekly['date']=df_weekly['date'].map(lambda date_string: datetime.datetime.strptime(date_string, "%Y-W%W-%w"))

In [24]:
df_weekly = df_weekly.drop('date_', axis=1)
df_weekly

,year_,week_,date,Ride_distance_sum,Ride_moving_time_sum,Ride_distance_max,Run_distance_sum,Run_moving_time_sum,Run_distance_max,Swim_distance_sum,Swim_moving_time_sum,Swim_distance_max
0,2019,19,2019-05-13,45.6,1.7,20.9,0.0,0.0,0.0,0.0,0.0,0.0
1,2019,25,2019-06-24,20.8,0.8,20.8,0.0,0.0,0.0,0.0,0.0,0.0
2,2019,28,2019-07-15,26.0,0.9,13.0,0.0,0.0,0.0,0.0,0.0,0.0
3,2020,5,2020-02-03,172.4,7.3,172.4,0.0,0.0,0.0,0.0,0.0,0.0
4,2020,7,2020-02-17,100.9,4.2,100.9,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
118,2022,20,2022-05-16,99.5,3.9,38.7,31.0,3.1,10.4,1.4,0.5,1.4
119,2022,21,2022-05-23,195.4,8.7,101.2,22.5,2.2,10.0,3.6,1.2,2.0
120,2022,22,2022-05-30,109.6,4.7,13.0,37.8,3.3,15.9,4.0,1.4,2.0
121,2022,23,2022-06-06,198.0,7.0,83.4,52.4,5.1,18.2,6.0,2.0,2.0
122,2022,24,2022-06-13,94.4,3.7,24.7,36.4,3.4,15.0,4.5,1.4,2.5

Loading health data

In [25]:
health =pd.read_csv('health.csv')

In [26]:
health.date

0      2022-06-17
1      2022-06-16
2      2022-06-15
3      2022-06-14
4      2022-06-13
          ...
255    2021-10-05
256    2021-10-04
257    2021-10-03
258    2021-10-02
259    2021-10-01
Name: date, Length: 260, dtype: object

In [27]:
#pd.to_datetime(health.date)

In [28]:
health.date = pd.to_datetime(health.date)

In [29]:
health['year'] = health['date'].apply(get_year)

health['week'] = health['date'].apply(get_week)

In [30]:
health.sort_values('date', ascending=False)

,date,score_sleep,Duree_sommeil,coucher,lever,FC_repos,FC_max_day,stress,training_status,training_comment,VO2_max_run,training_load,year,week
0,2022-06-17,40,247,0:25,6:02,54.0,89.0,24.0,Productif,Manque d'anaérobie,56.0,"1,292",2022,24
1,2022-06-16,NaN,NaN,NaN,NaN,61.0,199.0,48.0,Productif,Manque d'anaérobie,56.0,"1,578",2022,24
2,2022-06-15,38,337,23:40,5:48,58.0,177.0,43.0,Productif,Manque d'anaérobie,56.0,"1,549",2022,24
3,2022-06-14,No data,No data,No data,No data,51.0,180.0,52.0,Productif,Manque d'anaérobie,56.0,"1,565",2022,24
4,2022-06-13,85,425,22:50,6:25,42.0,167.0,34.0,Productif,Manque d'anaérobie,56.0,"1,572",2022,24
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
255,2021-10-05,NaN,NaN,NaN,NaN,62.0,193.0,23.0,Productif,Manque de charge d'aérobie faible,48.0,"4,590",2021,40
256,2021-10-04,NaN,NaN,NaN,NaN,64.0,172.0,20.0,Productif,Manque de charge d'aérobie faible,48.0,"3,741",2021,40
257,2021-10-03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Productif,Manque de charge d'aérobie faible,48.0,"3,020",2021,39
258,2021-10-02,NaN,NaN,NaN,NaN,66.0,188.0,24.0,Productif,Manque de charge d'aérobie faible,48.0,"3,323",2021,39
259,2021-10-01,NaN,NaN,NaN,NaN,NaN,NaN,20.0,Productif,Manque de charge d'aérobie faible,48.0,"3,768",2021,39

In [31]:
import numpy
health[health=='No data']=numpy.nan
health[health=='--']=numpy.nan

In [32]:
health

,date,score_sleep,Duree_sommeil,coucher,lever,FC_repos,FC_max_day,stress,training_status,training_comment,VO2_max_run,training_load,year,week
0,2022-06-17,40,247,0:25,6:02,54.0,89.0,24.0,Productif,Manque d'anaérobie,56.0,"1,292",2022,24
1,2022-06-16,NaN,NaN,NaN,NaN,61.0,199.0,48.0,Productif,Manque d'anaérobie,56.0,"1,578",2022,24
2,2022-06-15,38,337,23:40,5:48,58.0,177.0,43.0,Productif,Manque d'anaérobie,56.0,"1,549",2022,24
3,2022-06-14,NaN,NaN,NaN,NaN,51.0,180.0,52.0,Productif,Manque d'anaérobie,56.0,"1,565",2022,24
4,2022-06-13,85,425,22:50,6:25,42.0,167.0,34.0,Productif,Manque d'anaérobie,56.0,"1,572",2022,24
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
255,2021-10-05,NaN,NaN,NaN,NaN,62.0,193.0,23.0,Productif,Manque de charge d'aérobie faible,48.0,"4,590",2021,40
256,2021-10-04,NaN,NaN,NaN,NaN,64.0,172.0,20.0,Productif,Manque de charge d'aérobie faible,48.0,"3,741",2021,40
257,2021-10-03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Productif,Manque de charge d'aérobie faible,48.0,"3,020",2021,39
258,2021-10-02,NaN,NaN,NaN,NaN,66.0,188.0,24.0,Productif,Manque de charge d'aérobie faible,48.0,"3,323",2021,39
259,2021-10-01,NaN,NaN,NaN,NaN,NaN,NaN,20.0,Productif,Manque de charge d'aérobie faible,48.0,"3,768",2021,39

In [33]:
health.score_sleep=health.score_sleep.astype('float')
health.Duree_sommeil=health.Duree_sommeil.astype('float')
health.FC_repos=health.FC_repos.astype('float')
health.FC_max_day=health.FC_max_day.astype('float')
health.stress=health.stress.astype('float')
health.VO2_max_run=health.VO2_max_run.astype('float')
health.training_load=health.training_load.str.replace(',','').astype('float')

health.loc[:,['Duree_sommeil']]=health.loc[:,['Duree_sommeil']]/(60)

In [34]:
health_w=health.groupby(['week','year'],as_index=False).agg({'score_sleep': ['mean'],
                                                    'Duree_sommeil': ['mean'],
                                                    'FC_repos': ['mean'],
                                                    'FC_max_day': ['max'],
                                                    'stress':['mean'],
                                                    'VO2_max_run':['mean'],
                                                    'training_load':['mean']
                                                   
                                                   }).sort_values(by=['year','week'],ascending=[False,False]).round(1)

In [35]:
health_w

,week,year,score_sleep,Duree_sommeil,FC_repos,FC_max_day,stress,VO2_max_run,training_load
,,,mean,mean,mean,max,mean,mean,mean
38,52,2022,52.0,6.2,51.0,109.0,31.5,NaN,NaN
23,24,2022,54.3,5.6,53.2,199.0,40.2,56.0,1511.2
22,23,2022,50.0,6.4,46.7,207.0,35.6,56.0,1303.9
21,22,2022,57.8,6.4,47.9,185.0,33.0,57.0,1245.0
20,21,2022,61.4,6.5,46.9,193.0,26.7,57.0,1009.6
19,20,2022,53.7,6.0,50.9,204.0,36.3,57.0,542.7
18,19,2022,55.1,6.3,50.1,189.0,32.9,57.0,496.0
17,18,2022,51.3,5.9,50.3,185.0,30.7,57.0,1240.9
16,17,2022,42.1,6.3,54.1,189.0,35.9,56.0,1232.0
15,16,2022,72.2,6.6,45.7,189.0,28.1,56.0,886.9
14,15,2022,80.0,7.9,48.4,188.0,31.7,56.0,1839.0
13,14,2022,66.7,7.1,48.6,198.0,31.6,55.4,1695.0
12,13,2022,63.0,5.5,48.7,191.0,30.0,55.3,1826.7
11,12,2022,74.5,6.5,43.4,189.0,26.6,55.0,1780.0
10,11,2022,67.7,6.1,44.0,190.0,27.6,55.0,1392.3
9,10,2022,76.5,7.3,46.1,184.0,29.0,55.0,1051.0
8,9,2022,65.2,6.6,47.7,191.0,31.7,54.9,1235.4
7,8,2022,81.0,7.8,46.6,192.0,24.7,54.0,1341.1
6,7,2022,69.9,7.2,45.6,191.0,28.6,54.0,1647.6
5,6,2022,62.0,6.9,48.7,193.0,32.1,53.0,1837.4
4,5,2022,68.1,6.6,48.4,191.0,32.0,53.0,1342.4
3,4,2022,68.3,6.9,42.7,188.0,27.3,53.0,1157.7
2,3,2022,66.6,6.7,52.7,190.0,31.7,53.0,643.0
1,2,2022,58.8,6.8,52.0,183.0,31.8,53.2,178.8
0,1,2022,58.8,6.9,53.4,173.0,33.3,54.0,80.0
37,52,2021,68.6,7.4,47.6,112.0,26.8,54.0,291.3
36,51,2021,57.6,6.1,49.3,181.0,32.1,53.6,679.6
35,50,2021,71.0,7.0,47.6,187.0,28.0,53.7,799.4
34,49,2021,76.7,7.4,49.0,193.0,30.1,53.0,977.4
33,48,2021,61.6,6.0,52.5,195.0,34.3,53.0,408.1
32,47,2021,63.0,6.6,47.7,190.0,29.7,53.0,1168.7
31,46,2021,74.2,7.0,50.0,190.0,29.1,52.4,1353.0
30,45,2021,69.7,6.9,50.3,191.0,29.7,51.9,1285.4
29,44,2021,53.7,6.0,46.7,187.0,21.7,51.0,1876.6
28,43,2021,72.8,6.5,49.7,185.0,31.0,50.4,1901.1
27,42,2021,83.3,7.9,55.0,186.0,25.6,48.9,2291.9
26,41,2021,79.0,7.5,52.4,192.0,20.1,48.0,3179.1
25,40,2021,NaN,NaN,65.2,193.0,26.6,48.0,3956.1
24,39,2021,NaN,NaN,66.0,188.0,22.0,48.0,3370.3

In [36]:
health_w['date_']=health_w.year.map(str)+'-W'+health_w.week.map(str)+ '-1'

In [37]:
health_w.insert(2,'date',health_w['date_'])
health_w['date']=health_w['date'].map(lambda date_string: datetime.datetime.strptime(date_string, "%Y-W%W-%w"))

In [38]:
columns = health_w.columns.tolist()
health_w.columns = ['_'.join(tuple(reversed(list(col)))) for col in columns]

In [39]:
health_w

,_week,_year,_date,mean_score_sleep,mean_Duree_sommeil,mean_FC_repos,max_FC_max_day,mean_stress,mean_VO2_max_run,mean_training_load,_date_
38,52,2022,2022-12-26,52.0,6.2,51.0,109.0,31.5,NaN,NaN,2022-W52-1
23,24,2022,2022-06-13,54.3,5.6,53.2,199.0,40.2,56.0,1511.2,2022-W24-1
22,23,2022,2022-06-06,50.0,6.4,46.7,207.0,35.6,56.0,1303.9,2022-W23-1
21,22,2022,2022-05-30,57.8,6.4,47.9,185.0,33.0,57.0,1245.0,2022-W22-1
20,21,2022,2022-05-23,61.4,6.5,46.9,193.0,26.7,57.0,1009.6,2022-W21-1
19,20,2022,2022-05-16,53.7,6.0,50.9,204.0,36.3,57.0,542.7,2022-W20-1
18,19,2022,2022-05-09,55.1,6.3,50.1,189.0,32.9,57.0,496.0,2022-W19-1
17,18,2022,2022-05-02,51.3,5.9,50.3,185.0,30.7,57.0,1240.9,2022-W18-1
16,17,2022,2022-04-25,42.1,6.3,54.1,189.0,35.9,56.0,1232.0,2022-W17-1
15,16,2022,2022-04-18,72.2,6.6,45.7,189.0,28.1,56.0,886.9,2022-W16-1
14,15,2022,2022-04-11,80.0,7.9,48.4,188.0,31.7,56.0,1839.0,2022-W15-1
13,14,2022,2022-04-04,66.7,7.1,48.6,198.0,31.6,55.4,1695.0,2022-W14-1
12,13,2022,2022-03-28,63.0,5.5,48.7,191.0,30.0,55.3,1826.7,2022-W13-1
11,12,2022,2022-03-21,74.5,6.5,43.4,189.0,26.6,55.0,1780.0,2022-W12-1
10,11,2022,2022-03-14,67.7,6.1,44.0,190.0,27.6,55.0,1392.3,2022-W11-1
9,10,2022,2022-03-07,76.5,7.3,46.1,184.0,29.0,55.0,1051.0,2022-W10-1
8,9,2022,2022-02-28,65.2,6.6,47.7,191.0,31.7,54.9,1235.4,2022-W9-1
7,8,2022,2022-02-21,81.0,7.8,46.6,192.0,24.7,54.0,1341.1,2022-W8-1
6,7,2022,2022-02-14,69.9,7.2,45.6,191.0,28.6,54.0,1647.6,2022-W7-1
5,6,2022,2022-02-07,62.0,6.9,48.7,193.0,32.1,53.0,1837.4,2022-W6-1
4,5,2022,2022-01-31,68.1,6.6,48.4,191.0,32.0,53.0,1342.4,2022-W5-1
3,4,2022,2022-01-24,68.3,6.9,42.7,188.0,27.3,53.0,1157.7,2022-W4-1
2,3,2022,2022-01-17,66.6,6.7,52.7,190.0,31.7,53.0,643.0,2022-W3-1
1,2,2022,2022-01-10,58.8,6.8,52.0,183.0,31.8,53.2,178.8,2022-W2-1
0,1,2022,2022-01-03,58.8,6.9,53.4,173.0,33.3,54.0,80.0,2022-W1-1
37,52,2021,2021-12-27,68.6,7.4,47.6,112.0,26.8,54.0,291.3,2021-W52-1
36,51,2021,2021-12-20,57.6,6.1,49.3,181.0,32.1,53.6,679.6,2021-W51-1
35,50,2021,2021-12-13,71.0,7.0,47.6,187.0,28.0,53.7,799.4,2021-W50-1
34,49,2021,2021-12-06,76.7,7.4,49.0,193.0,30.1,53.0,977.4,2021-W49-1
33,48,2021,2021-11-29,61.6,6.0,52.5,195.0,34.3,53.0,408.1,2021-W48-1
32,47,2021,2021-11-22,63.0,6.6,47.7,190.0,29.7,53.0,1168.7,2021-W47-1
31,46,2021,2021-11-15,74.2,7.0,50.0,190.0,29.1,52.4,1353.0,2021-W46-1
30,45,2021,2021-11-08,69.7,6.9,50.3,191.0,29.7,51.9,1285.4,2021-W45-1
29,44,2021,2021-11-01,53.7,6.0,46.7,187.0,21.7,51.0,1876.6,2021-W44-1
28,43,2021,2021-10-25,72.8,6.5,49.7,185.0,31.0,50.4,1901.1,2021-W43-1
27,42,2021,2021-10-18,83.3,7.9,55.0,186.0,25.6,48.9,2291.9,2021-W42-1
26,41,2021,2021-10-11,79.0,7.5,52.4,192.0,20.1,48.0,3179.1,2021-W41-1
25,40,2021,2021-10-04,NaN,NaN,65.2,193.0,26.6,48.0,3956.1,2021-W40-1
24,39,2021,2021-09-27,NaN,NaN,66.0,188.0,22.0,48.0,3370.3,2021-W39-1

In [40]:
df_weekly

,year_,week_,date,Ride_distance_sum,Ride_moving_time_sum,Ride_distance_max,Run_distance_sum,Run_moving_time_sum,Run_distance_max,Swim_distance_sum,Swim_moving_time_sum,Swim_distance_max
0,2019,19,2019-05-13,45.6,1.7,20.9,0.0,0.0,0.0,0.0,0.0,0.0
1,2019,25,2019-06-24,20.8,0.8,20.8,0.0,0.0,0.0,0.0,0.0,0.0
2,2019,28,2019-07-15,26.0,0.9,13.0,0.0,0.0,0.0,0.0,0.0,0.0
3,2020,5,2020-02-03,172.4,7.3,172.4,0.0,0.0,0.0,0.0,0.0,0.0
4,2020,7,2020-02-17,100.9,4.2,100.9,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
118,2022,20,2022-05-16,99.5,3.9,38.7,31.0,3.1,10.4,1.4,0.5,1.4
119,2022,21,2022-05-23,195.4,8.7,101.2,22.5,2.2,10.0,3.6,1.2,2.0
120,2022,22,2022-05-30,109.6,4.7,13.0,37.8,3.3,15.9,4.0,1.4,2.0
121,2022,23,2022-06-06,198.0,7.0,83.4,52.4,5.1,18.2,6.0,2.0,2.0
122,2022,24,2022-06-13,94.4,3.7,24.7,36.4,3.4,15.0,4.5,1.4,2.5

In [41]:
weekly = pd.merge(df_weekly,health_w,how='left',left_on=['year_','week_'],right_on=['_year','_week'])

In [42]:
weekly.drop(['_date_', '_week', '_year', '_date'],axis=1,inplace=True)

In [43]:
weekly.columns

Index(['year_', 'week_', 'date', 'Ride_distance_sum', 'Ride_moving_time_sum',
       'Ride_distance_max', 'Run_distance_sum', 'Run_moving_time_sum',
       'Run_distance_max', 'Swim_distance_sum', 'Swim_moving_time_sum',
       'Swim_distance_max', 'mean_score_sleep', 'mean_Duree_sommeil',
       'mean_FC_repos', 'max_FC_max_day', 'mean_stress', 'mean_VO2_max_run',
       'mean_training_load'],
      dtype='object')

Loading the dataframe on Googlesheet

In [44]:
import warnings
warnings.filterwarnings("ignore")
# For connect to google sheet
import gspread
from oauth2client.service_account import ServiceAccountCredentials
from df2gspread import df2gspread as d2g

In [45]:
# Configure the connection 
scope = ['https://spreadsheets.google.com/feeds']

# Give the path to the Service Account Credential json file 
credentials = ServiceAccountCredentials.from_json_keyfile_name('service_account_GS.json',
                                                               scope
                                                              )
# Authorise your Notebook
gc = gspread.authorize(credentials)

# The sprad sheet ID, which can be taken from the link to the sheet
spreadsheet_key = '1vNnbAl7kMQHeL-UbkL8hTY93Z_3areu195dUuV7ooMA'
#

In [46]:
# Set the sheet name you want to upload data to and the start cell where the upload data begins 
wks_name = 'week'
cell_of_start_df = 'C2'
# upload the dataframe of the clients we want to delete
d2g.upload(weekly,
           spreadsheet_key,
           wks_name,
           credentials=credentials,
           col_names=False,
           row_names=False,
           start_cell = cell_of_start_df,
           clean=False)